services:
#  app:
#    build: ./
#    ports:
#      - "8080:8080"
#    depends_on:
#      - thanos-receive
#    networks:
#      - thanos-network
#  prometheus: ##TODO , do not work some malformed req/res error when connecting to local thanos
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    networks:
#      - thanos-network
  thanos-receive:
    image: quay.io/thanos/thanos:v0.31.0
    container_name: thanos-receive
    command:
      - receive
      - --receive.local-endpoint=0.0.0.0:10901
      - --tsdb.path=/var/thanos/receive
      - --log.level=debug
      - --log.format=logfmt
      - --label=receive_replica="0"
      - --label=receive_cluster="local"
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --receive.grpc-compression=snappy
      - --receive.hashrings-file=/etc/thanos/hashring.json
      - --remote-write.address=0.0.0.0:10908
    ports:
      - "10901:10901"
      - "10902:10902"
    volumes:
      - ./hashring.json:/etc/thanos/hashring.json
      - thanos-receive-data:/var/thanos/receive
    networks:
      - thanos-network
  thanos-query:
    image: quay.io/thanos/thanos:v0.31.0
    command:
      - query
      - --http-address=0.0.0.0:10902
      - --store=thanos-receive:10901
      - --log.level=debug
    ports:
      - "9091:10902"
    networks:
      - thanos-network
  thanos-store:
    image: quay.io/thanos/thanos:v0.31.0
    command:
      - store
      - --data-dir=/var/thanos/store
      - --objstore.config-file=/etc/thanos/bucket.yml
      - --grpc-address=0.0.0.0:10905
      - --http-address=0.0.0.0:10906
    ports:
      - "10905:10905"
      - "10906:10906"
    volumes:
      - thanos-store-data:/var/thanos/store
      - ./bucket.yml:/etc/thanos/bucket.yml
    networks:
      - thanos-network
networks:
  thanos-network:
    driver: bridge
volumes:
  thanos-receive-data:
  thanos-store-data:

# Local Thanos http://localhost:9091