global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheusLocal'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]

remote_write:
  - url: 'http://thanos-receive:10901/api/v1/receive'
