global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheusExporterJobLocal'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

remote_write:
  - url: 'http://thanos-receive:10908/api/v1/receive'
    name: 'prometheusExporterJobLocal'
