global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheusScrapeJobLocal'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

remote_write:
  - url: 'http://thanos-receive:10908/api/v1/receive'
    name: 'prometheusPushExporterLocal'
    write_relabel_configs:
      - action: labeldrop
        source_labels: [ exception,outcome,uri ]
        regex: '.*'
      - action: labelmap
        source_labels: [ exporterName ]
        replacement: "localPrometheusExporter_ashbha"
